### ISSUE TITLE
Bug when moving scattered tokens with mouse:  they remain offset from grid, until moves once more (Drag Ruler compatibility issue)

### ISSUE THREAD

**Issue by shemetz** [elizeuangelo/fvtt-module-z-scatter#4] opened 2023-03-14 16:41 UTC
(I can provide more details if this doesn't get reproduced)

Before & After dragging the token from the "stack" into the square two spaces to the right:

![image](https://user-images.githubusercontent.com/6516621/225076041-3b41bc02-2a0f-4a23-b621-3c036b5531b2.png)

![image](https://user-images.githubusercontent.com/6516621/225076077-55cdf3bc-97e5-4cd7-98e2-f634b3553f14.png)

**Comment by shemetz** [comment] 2023-03-14 16:42
note that dragging once more, even into the same square, works as a workaround:
![image](https://user-images.githubusercontent.com/6516621/225076232-32e7e4d4-218d-40d7-acbf-1f85bac77c73.png)

**Comment by elizeuangelo** [comment] 2023-03-14 16:45
Im not able to reproduce this. What version of Foundry and system are you using? Could you call me in discord? Magus#9576

**Comment by elizeuangelo** [comment] 2023-03-14 16:47
Im not able to reproduce this? What version of Foundry and system are you using?

**Comment by elizeuangelo** [comment] 2023-03-14 16:54
There is a bugged function in _Core Foundry_ related to token movement wich the modules "fixes".

I reported the bug in Core and I hope it gets fixed soon, but maybe that other module tries fixing it as well using some other method.

In Core Foundry v10.291 (all modules disabled) if you have the token "shifted" to the left or upside a square (by holding shift), it jumps 2 squares if moving left or top.

**Comment by shemetz** [comment] 2023-03-14 17:06
The module "incompatibility" here is apparently with Drag Ruler.  I'll update the title of this ticket.

Regarding your comment - I think you accidentally swapped your comments for #5 and #4?

**Comment by elizeuangelo** [comment] 2023-03-14 23:12
Fixed in v1.2.7

**Closed by elizeuangelo** 2023-03-14 23:12 UTC
